services:
  db:
    image: postgres:17.4
    environment:
      POSTGRES_USER: postus
      PGUSER: postus
      POSTGRES_PASSWORD: passus
      POSTGRES_DB: tic-tat-toe-db
      PGDATA: /data/postgres
    ports:
      - "1234:5432"
    volumes:
      - db:/data/postgres
    networks:
      - db
    restart: unless-stopped
    healthcheck:
      test: [ "CMD", "pg_isready", "-U", "postus", "-d", "tic-tat-toe-db" ]
      interval: 30s
      timeout: 10s
      retries: 5
  web:
    depends_on:
      - db
    build:
      dockerfile: Dockerfile
    ports:
      - "0.0.0.0:8080:8080"
    environment:
      - FIELD_SIZE=3
      - WIN_CONDITION=3
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:8080
    networks:
      - db

networks:
  db:
    driver: bridge

volumes:
  db: